apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app: {{ include "app-python.fullname" . }}
    chart: {{ include "app-python.chart" . }}
type: Opaque
data:
  username: {{ .Values.secrets.username | b64enc | quote }}